import {expect,test,type Page} from '@playwright/test';
async function outsideViewport(page:Page){return page.locator('header.site-header').evaluate(header=>[...header.querySelectorAll('a,button')].filter(el=>!!(el as HTMLElement).offsetParent).filter(el=>{const r=el.getBoundingClientRect();return r.left<0||r.right>innerWidth}).map(el=>el.textContent))}
test('antetul si titlul sunt utilizabile la cinci latimi',async({page})=>{for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:900});await page.goto('/');expect(await outsideViewport(page)).toEqual([]);await expect(page.locator('h1')).toBeVisible()}});
test('contractul se deschide pe pagina sursa, permite parcurgere si descarcare',async({page})=>{
 await page.goto('/cum-functioneaza#demonstratie');const demo=page.getByTestId('search-demo');const source=demo.locator('.source-card');await source.click();const dialog=page.getByRole('dialog',{name:'Contract de servicii · DEMO-024'});await expect(dialog).toBeVisible();await expect(dialog.locator('mark')).toHaveText('4.2. Termenul de plată este de 30 de zile calendaristice de la primirea facturii.');await expect(dialog.locator('.source-toolbar')).toContainText('Pagina 2 din 2');await dialog.getByRole('button',{name:'Pagina precedentă'}).click();await expect(dialog.locator('.source-page')).toContainText('1. Părți');await expect(dialog.getByRole('button',{name:'Pagina precedentă'})).toBeDisabled();await dialog.getByRole('button',{name:'Pagina următoare'}).click();await expect(dialog.locator('mark')).toBeVisible();
 const download=page.waitForEvent('download');await dialog.getByRole('link',{name:'Descărcați exemplul PDF'}).click();expect((await download).suggestedFilename()).toBe('contract.pdf');
 for(let i=0;i<9;i++){await page.keyboard.press('Tab');expect(await page.evaluate(()=>!!document.activeElement?.closest('dialog'))).toBe(true)}await page.keyboard.press('Escape');await expect(dialog).toBeHidden();await expect(source).toBeFocused();
});
test('fiecare exemplu schimba intrebarea, raspunsul si documentul',async({page})=>{await page.goto('/');const demo=page.getByTestId('search-demo');for(const [label,answer,title] of [['Factură','Atelier Exemplu SRL','Factură fictivă'],['Proces-verbal','P-04','Recepție lucrări'],['Contract','30 de zile','Contract de servicii']]){await demo.locator('.demo-options').getByRole('button',{name:label,exact:true}).click();await expect(demo.locator('.answer')).toContainText(answer);await expect(demo.locator('.source-card')).toContainText(title);await demo.locator('.source-card').click();await expect(page.getByRole('dialog')).toContainText(title);await page.keyboard.press('Escape')}});
test('intrebarile fara sursa nu primesc raspuns inventat',async({page})=>{await page.goto('/');const demo=page.getByTestId('search-demo');await demo.getByRole('button',{name:'Fără rezultat'}).click();await expect(demo.locator('.answer')).toContainText('Document negăsit');await expect(demo.locator('.source-card')).toHaveCount(0);await demo.getByRole('textbox').fill('Când expiră contractul?');await demo.getByRole('button',{name:'Căutați în exemple'}).click();await expect(demo.locator('.source-card')).toHaveCount(0);await demo.getByRole('textbox').fill('Care este termenul de plata?');await demo.getByRole('textbox').press('Enter');await expect(demo.locator('.answer')).toContainText('30 de zile')});
test('contactul pastreaza domeniul si pregateste mesajul fara cerere de trimitere',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);await page.goto('/solutii/notari');await page.getByRole('link',{name:'Cereți o evaluare',exact:true}).click();await expect(page.getByLabel('Despre ce doriți să discutăm?')).toHaveValue('Evaluare arhivă birou notarial');await page.getByLabel('Câteva detalii despre arhivă').fill('Avem 12 cutii în Golești.');const link=page.getByRole('link',{name:'Deschideți e-mailul'});const href=await link.getAttribute('href');const url=new URL(href!);expect(url.protocol).toBe('mailto:');expect(url.pathname).toBe('office@adriaarhivare.ro');expect(url.searchParams.get('subject')).toContain('notarial');expect(url.searchParams.get('body')).toContain('12 cutii în Golești');await page.getByRole('button',{name:'Copiați mesajul',exact:true}).click();await expect(page.getByRole('status')).toContainText('Mesajul a fost copiat');expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('12 cutii în Golești');await page.getByRole('button',{name:'Copiați adresa de e-mail'}).click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('office@adriaarhivare.ro');
});
test('ghidul filtreaza, trateaza cautarea fara rezultat si calculeaza regula corecta',async({page})=>{
 await page.goto('/instrumente/termene-de-pastrare');await page.getByRole('button',{name:'Salarizare',exact:true}).click();await expect(page.locator('.retention-row')).toHaveCount(1);await expect(page.locator('.retention-row')).toContainText('State de salarii');await page.getByRole('searchbox').fill('inexistent');await expect(page.locator('.retention-row')).toHaveCount(0);await page.getByRole('button',{name:'Resetați filtrele'}).click();await expect(page.locator('.retention-row')).toHaveCount(4);await page.getByRole('spinbutton').fill('2024');await expect(page.locator('#year-result')).toContainText('1 iulie 2025');await expect(page.locator('#year-result')).toContainText('1 iulie 2030');await page.getByRole('spinbutton').fill('');await expect(page.locator('#year-result')).toContainText('Introduceți un an întreg');
});
test('planificarea costurilor transfera selectia in contact si cere cel putin un serviciu',async({page})=>{await page.goto('/investitia');await page.getByRole('checkbox',{name:'Digitalizare'}).uncheck();await expect(page.getByRole('status')).toContainText('Selectați cel puțin un serviciu');await expect(page.getByRole('link',{name:'Continuați cu acest context'})).toHaveCount(0);await page.getByRole('checkbox',{name:'Păstrare fizică'}).check();await page.getByLabel('Volum aproximativ').selectOption('Un dulap sau o cameră');await page.getByRole('link',{name:'Continuați cu acest context'}).click();await expect(page.getByLabel('Despre ce doriți să discutăm?')).toHaveValue('Evaluare: Păstrare fizică · Un dulap sau o cameră')});
test('comparatia mobila permite alegerea tuturor variantelor',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/comparatie');for(const [value,text] of [['0','Rămâne la sediul organizației.'],['1','Originalele sunt păstrate la operator.'],['2','Locul originalelor se stabilește separat de accesul digital.']]){await page.getByLabel('Varianta de analizat').selectOption(value);await expect(page.locator('.comparison-row').first().locator('.mobile-selected')).toHaveText(text)}});
test('preferinta pentru miscare redusa opreste animatia decorativa',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');expect(await page.locator('.hero-spectrum').evaluate(el=>getComputedStyle(el).animationName)).toBe('none')});
test('o adresa inexistenta raspunde 404 si ofera recuperare',async({page})=>{const response=await page.goto('/pagina-care-nu-exista');expect(response?.status()).toBe(404);await expect(page.locator('h1')).toHaveText('Pagina nu a fost găsită.');await page.getByRole('link',{name:'Înapoi la început'}).click();await expect(page).toHaveURL(/\/$/)});
test('martor POZITIV: detecteaza actiunea din afara ferestrei',async({page})=>{await page.setViewportSize({width:390,height:844});await page.setContent('<header class="site-header"><a href="/" style="position:absolute;left:500px">Depaseste</a></header>');expect(await outsideViewport(page)).toEqual(['Depaseste'])});
test('martor NEGATIV: ignora actiunile ascunse',async({page})=>{await page.setContent('<header class="site-header"><a href="/">Corect</a><a style="display:none;position:absolute;left:500px">Ascuns</a></header>');expect(await outsideViewport(page)).toEqual([])});
