import type {Metadata} from "next";
import {Action,CTA,Eyebrow,Photo} from "@/components/Elements";
import Icon from "@/components/Icon";

export const metadata:Metadata={"title": "Arhivare fizică și păstrarea documentelor prin ADRIA", "description": "Organizarea, inventarierea și păstrarea documentelor prin ADRIA. Aflați ce se stabilește la preluare și cum se pregătește consultarea.", "alternates": {"canonical": "/arhivare-fizica"}};
export default function Page(){return <main>
<section className="container physical-hero"><div><Eyebrow>Store / Arhivare fizică</Eyebrow><h1>Un loc pentru dosar.<br/>Un reper pentru a-l regăsi.</h1><p className="lead">Păstrarea începe cu identificarea documentelor. Serviciile de arhivare fizică sunt oferite prin ADRIA SERVICII ARHIVARE SRL.</p><Action label="Cereți evaluarea arhivei" context="Evaluare arhivare fizică"/></div><Photo kind="archive"/></section>
<section className="container section"><div className="section-heading"><div><Eyebrow>Înainte de mutarea unei cutii</Eyebrow><h2>Inventarul face diferența.</h2></div><p>O referință consecventă leagă documentul de cutie și de poziția din evidență. Modelul se adaptează fondului dumneavoastră.</p></div><div className="inventory-example"><div className="inventory-title"><Icon name="box"/><h3>Exemplu de inventar</h3><span>Date fictive</span></div><div className="inventory-row inventory-labels"><span>Referință</span><span>Conținut</span><span>Perioadă</span><span>Unitate</span></div>{[["AR-001","Documente contabile","2025","Cutia 01"],["AR-002","Contracte furnizori","2024-2025","Cutia 02"],["AR-003","Dosar proiect Nord","2023-2025","Cutia 03"]].map(r=><div className="inventory-row" key={r[0]}>{r.map(c=><span key={c}>{c}</span>)}</div>)}</div></section>
<section className="soft-section"><div className="container section"><Eyebrow>Ce se agreează în proiect</Eyebrow><div className="three-columns"><article><Icon name="box" size={30}/><h2>Preluarea</h2><p>Documentele incluse, starea lor, inventarul, ambalarea, transportul și procesul-verbal de predare-primire.</p></article><article><Icon name="search" size={30}/><h2>Consultarea</h2><p>Cine poate solicita un document, dacă este necesară copia sau originalul și în ce condiții se livrează.</p></article><article><Icon name="shield" size={30}/><h2>Finalul păstrării</h2><p>Returul, transferul sau selecționarea se tratează separat. Expirarea unui termen nu declanșează automat distrugerea.</p></article></div></div></section>
<section className="container section location-section"><div><Eyebrow>Operatorul de arhivare</Eyebrow><h2>ADRIA, la Golești.</h2><p>ADRIA SERVICII ARHIVARE SRL<br/>CUI 30901492 · J03/1580/2012</p><address>Strada Gării nr. 29 bis, Hala C1<br/>Golești, Argeș, 117721</address><a className="text-link" href="https://adriaarhivare.ro/contact.html" target="_blank" rel="noreferrer">Date publice de contact ADRIA (filă nouă)<Icon/></a></div><div><h3>O vizită se stabilește în prealabil.</h3><p>Adresa de mai sus este punctul de lucru publicat de ADRIA. Scrieți pentru a confirma disponibilitatea și persoana care vă poate primi.</p><Action label="Solicitați o vizită" context="Solicitare vizită la punctul de lucru ADRIA"/></div></section><CTA context="Evaluare arhivare fizică"/>
</main>;}
