import type {Metadata} from "next";
import Link from "next/link";
import {Action,CTA,Eyebrow,Photo,Questions,SectorLinks} from "@/components/Elements";
import Icon from "@/components/Icon";
import SearchDemo from "@/components/SearchDemo";
export const metadata:Metadata={"title": "Arhivare și digitalizare | Scan Store Solve", "description": "Arhivare fizică prin ADRIA, digitalizare și căutare în documente. Explorați demonstrația 3S și începeți cu o evaluare a arhivei.", "alternates": {"canonical": "/"}};
export default function Page(){return <main>
<section className="home-hero"><div className="hero-spectrum" aria-hidden="true"/><div className="container hero-grid"><div className="hero-copy"><Eyebrow>Scan. Store. Solve.</Eyebrow><h1>Arhiva în ordine.{" "}<br/>Informația{" "}<br/><span>la îndemână.</span></h1><p className="lead">De la documentul pe hârtie la răspunsul de care aveți nevoie. Arhivare fizică, digitalizare și căutare, gândite împreună.</p><div className="hero-actions"><Action label="Să discutăm"/><Link className="text-link" href="/cum-functioneaza">Descoperiți serviciile<Icon/></Link></div><p className="hero-footnote">Arhivare și digitalizare prin ADRIA.{" "}<br/>Explorați alături un exemplu de căutare 3S.</p></div><div className="hero-product" id="demonstratie"><div className="product-overline"><span>DIN DOCUMENT, DIRECT LA RĂSPUNS</span><span className="product-line"/></div><SearchDemo compact/><div className="product-caption"><Icon name="file" size={16}/><span>Întrebați. Citiți răspunsul. Deschideți sursa.</span></div></div></div></section>
<div className="service-ribbon"><div className="container"><span><Icon name="scan"/>Digitalizare</span><span><Icon name="box"/>Arhivare fizică</span><span><Icon name="search"/>Căutare în documente</span><Link href="/despre">Experiența ADRIA, în proiectul 3S<Icon size={16}/></Link></div></div>
<section className="container section" id="servicii"><div className="section-heading"><div><Eyebrow>De la hârtie la informație</Eyebrow><h2>Trei servicii.{" "}<br/>Un singur fir.</h2></div><p>Începem cu documentele pe care le aveți. Alegem împreună ce trebuie organizat, păstrat și făcut mai ușor de consultat.</p></div><div className="service-grid"><article className="service-feature"><span className="service-number">01</span><div className="service-symbol scan-symbol"><Icon name="scan" size={42}/></div><p className="service-name">Scan</p><h3>Hârtia devine accesibilă.</h3><p>Pregătire, scanare, verificarea imaginilor și indexare după câmpurile folosite în activitatea dumneavoastră.</p><Link className="text-link" href="/cum-functioneaza#digitalizare">Despre digitalizare<Icon/></Link></article><article className="service-feature"><span className="service-number">02</span><div className="service-symbol store-symbol"><Icon name="box" size={42}/></div><p className="service-name">Store</p><h3>Fiecare dosar are un loc.</h3><p>Inventarierea și păstrarea fizică prin ADRIA leagă documentul de o referință, de un responsabil și de o procedură de consultare.</p><Link className="text-link" href="/arhivare-fizica">Despre arhivare<Icon/></Link></article><article className="service-feature"><span className="service-number">03</span><div className="service-symbol solve-symbol"><Icon name="search" size={42}/></div><p className="service-name">Solve</p><h3>Răspunsul are o sursă.</h3><p>Descoperiți principiul căutării în documente: întrebare, răspuns și pagina de verificat. Funcțiile unui proiect real se stabilesc la evaluare.</p><Link className="text-link" href="#demonstratie">Încercați demonstrația<Icon/></Link></article></div></section>
<section className="operations-section"><div className="container operations-grid"><div><Eyebrow>O muncă atentă, înainte de orice tehnologie</Eyebrow><h2>Un document bun{" "}<br/>începe cu o preluare bună.</h2><p>Ordinea dosarelor, starea hârtiei și identificatorii contează. Digitalizarea este utilă când păstrează contextul documentului.</p><div className="operations-points"><div><span>01</span><p><strong>Înțelegem arhiva.</strong> Evaluăm tipurile de documente și felul în care sunt consultate.</p></div><div><span>02</span><p><strong>Stabilim regulile.</strong> Inventar, indexare, predare și verificări, înainte de lucru.</p></div><div><span>03</span><p><strong>Verificăm pe un eșantion.</strong> Confirmați lizibilitatea și structura, apoi dimensionăm proiectul.</p></div></div><Link className="text-link" href="/cum-functioneaza">Parcurgeți procesul complet<Icon/></Link></div><Photo kind="scan"/></div></section>
<section className="container section" id="domenii"><div className="section-heading"><div><Eyebrow>Organizare după activitate</Eyebrow><h2>Arhiva nu arată{" "}<br/>la fel în fiecare domeniu.</h2></div><p>Un dosar de șantier se caută altfel decât o factură sau un act notarial. Pornim de la reperele dumneavoastră.</p></div><SectorLinks/></section>
<section className="resource-strip container"><Icon name="clock" size={34}/><div><p className="eyebrow">Ghid practic</p><h2>Cât timp se păstrează documentele?</h2><p>Regula contabilă, sursele oficiale și un calcul orientativ, într-un singur loc.</p></div><Link className="text-link" href="/instrumente/termene-de-pastrare">Consultați ghidul<Icon/></Link></section>
<section className="container section faq-section"><div><Eyebrow>Înainte să începem</Eyebrow><h2>Întrebări firești.{" "}<br/>Răspunsuri directe.</h2></div><Questions/></section><CTA/>
</main>;}
