export const EMAIL = "office@adriaarhivare.ro";
export const SOURCE_ADRIA = "https://adriaarhivare.ro/contact.html";
export const SOURCE_ACCOUNTING = "https://legislatie.just.ro/public/DetaliiDocument/263884";
export const SOURCE_ARCHIVES = "https://legislatie.just.ro/Public/DetaliiDocument/7937";
export const REVIEW_DATE = "19 septembrie 2026";
export function emailLink(subject = "Proiect de arhivare 3S", body = "Bună ziua,\n\nAș dori să discutăm despre arhivarea documentelor organizației noastre.\n") {
  return `mailto:${EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}
export type Sector = { slug:string; name:string; short:string; tag:string; title:string; intro:string; color:string; file:string; fields:[string,string][]; problem:string; outcome:string; steps:[string,string][]; question:string; answer:string; request:string; related:string };
export const SECTORS: Sector[] = [
 {slug:"constructii",name:"Construcții",short:"De la șantier la cartea tehnică.",tag:"Proiecte & execuție",title:"Fiecare proiect, cu documentele la locul lor.",intro:"Planuri revizuite, procese-verbale și recepții: un dosar urmărit pe obiectiv, etapă și versiune, de la execuție până la predare.",color:"blue",file:"Recepție lucrări · corp B",fields:[["Obiectiv","Atelier Nord"],["Etapă","Instalații"],["Revizie","03 / 2026"],["Tip document","Proces-verbal"]],problem:"O planșă veche nu trebuie confundată cu ultima revizie.",outcome:"Propunem o structură de inventar care păstrează împreună identificatorul proiectului, disciplina, data și revizia. Originalul și copia digitală primesc aceeași referință.",steps:[["Separare pe obiective","Dosarele unui șantier rămân distincte de cele ale altui proiect."],["Controlul versiunilor","Stabilim cum se marchează reviziile și care document este valabil pentru etapa respectivă."],["Pregătirea predării","Definim lista documentelor, lipsurile de completat și formatul de predare pentru beneficiar."]],question:"Putem începe cu un singur șantier?",answer:"Da. Evaluarea poate porni de la un obiectiv și un eșantion de dosare. Dimensiunile planșelor, starea hârtiei și numărul de revizii stabilesc modul de digitalizare și oferta.",request:"Evaluare dosar de șantier",related:"imobiliare"},
 {slug:"logistica",name:"Transport & logistică",short:"Dovada livrării, legată de cursă.",tag:"Curse & livrări",title:"O cursă se încheie. Documentele rămân ușor de găsit.",intro:"Legați scrisoarea de trăsură, avizul și dovada de livrare de aceeași cursă. Un model de organizare gândit pentru documente care sosesc zilnic.",color:"teal",file:"Dosar cursă · RO-0248",fields:[["Cursă","RO-0248"],["Client","Exemplu Logistic"],["Lună","Septembrie 2026"],["Document","Dovadă de livrare"]],problem:"Factura este pregătită, dar dovada livrării lipsește din dosar.",outcome:"Inventarul propus pornește de la identificatorul cursei. Documentele primite ulterior se adaugă la aceeași referință, iar lipsurile pot fi urmărite într-o listă separată.",steps:[["Loturi după fluxul real","Agreăm preluarea pe săptămână sau pe lună, după volumul documentelor."],["O cheie comună","Cursa, clientul și data leagă documentele operaționale de cele contabile."],["Verificarea dosarului","Stabilim ce înseamnă un dosar complet și cum se semnalează documentele lipsă."]],question:"Se pot include fotografii și documente deja scanate?",answer:"Le evaluăm împreună cu documentele pe hârtie. Lizibilitatea, orientarea și identificatorii disponibili influențează indexarea; un fișier neclar trebuie cerut din nou, nu completat prin presupuneri.",request:"Evaluare arhivă de transport",related:"contabilitate"},
 {slug:"imobiliare",name:"Imobiliare",short:"Dosarul proprietății, într-un singur fir.",tag:"Proprietăți & tranzacții",title:"Toată povestea unei proprietăți. Într-un dosar coerent.",intro:"Contractele, planurile și actele unei tranzacții se organizează după proprietate și etapă, cu atenție la datele personale și la copiile care circulă.",color:"orange",file:"Dosar proprietate · IM-014",fields:[["Referință","IM-014"],["Proprietate","Spațiu comercial Nord"],["Etapă","Verificare documente"],["Categorie","Contract de reprezentare"]],problem:"Aceeași proprietate apare în mai multe conversații și foldere.",outcome:"Un identificator stabil de proprietate păstrează documentele împreună chiar dacă adresa, agentul responsabil sau stadiul tranzacției se schimbă.",steps:[["Identificarea proprietății","Definim referința internă și câmpurile utile pentru regăsire."],["Separarea tranzacțiilor","Documentele fiecărei tranzacții au propria structură și perioadă."],["Acces după responsabilitate","Lista persoanelor și documentele la care au nevoie de acces se stabilesc înaintea configurării digitale."]],question:"Este necesară copierea tuturor actelor de identitate?",answer:"Nu presupunem acest lucru. Organizația stabilește ce documente sunt necesare, temeiul și perioada de păstrare; copiile inutile nu trebuie adăugate automat în arhivă.",request:"Evaluare dosare imobiliare",related:"avocatura"},
 {slug:"primarii",name:"Instituții publice",short:"Continuitate dincolo de un mandat.",tag:"Administrație & patrimoniu",title:"O arhivă care păstrează continuitatea instituției.",intro:"Fonduri din ani diferiți, compartimente și cereri ale cetățenilor: organizarea începe cu proveniența documentelor și cu nomenclatorul instituției.",color:"purple",file:"Inventar · compartiment urbanism",fields:[["Compartiment","Urbanism"],["An","2024"],["Categorie","Corespondență"],["Referință","U-024 / exemplu"]],problem:"O schimbare de personal nu ar trebui să întrerupă regăsirea documentelor.",outcome:"Inventarul propus leagă fiecare unitate arhivistică de compartiment, an și categoria din nomenclator. Fondurile istorice se identifică separat, înainte de reorganizare.",steps:[["Evaluarea fondului","Identificăm perioadele, compartimentele și instrumentele de evidență existente."],["Nomenclator și inventare","Raportăm organizarea la nomenclatorul aplicabil, fără să atribuim un termen universal tuturor documentelor."],["Predare între responsabili","Definim evidența documentelor preluate și a cererilor de consultare."]],question:"Pot fi eliminate documente imediat ce expiră termenul?",answer:"Nu automat. Expirarea termenului și procedura de selecționare sunt lucruri distincte. Legea Arhivelor Naționale prevede evaluarea și aprobările aplicabile înainte de scoaterea documentelor din evidență.",request:"Evaluare fond arhivistic instituție",related:"contabilitate"},
 {slug:"contabilitate",name:"Contabilitate",short:"Fiecare firmă, fiecare exercițiu.",tag:"Financiar & evidență",title:"Mai puțin timp între o întrebare și documentul justificativ.",intro:"Un fond separat pe client și exercițiu financiar. Facturile, registrele și documentele salariale se regăsesc după aceleași reguli, fără amestec între firme.",color:"purple",file:"Document justificativ · EX-026",fields:[["Entitate","Companie Exemplu"],["Exercițiu","2025"],["Categorie","Facturi furnizori"],["Referință","EX-026"]],problem:"Un control solicită exact documentul pe care nu îl mai găsește nimeni.",outcome:"Câmpurile de indexare pornesc de la firmă, an, tip, număr și dată. Scanarea și verificarea lizibilității au roluri separate, iar originalele își păstrează referința.",steps:[["Fonduri distincte","Păstrăm separarea documentelor fiecărei persoane juridice."],["Index util la control","Alegem împreună câmpurile după care căutați în activitatea curentă."],["Termene verificate","Art. 25 din Legea contabilității prevede 5 ani, inclusiv pentru statele de salarii; calculul începe la 1 iulie din anul următor încheierii exercițiului financiar."]],question:"Toate documentele unei firme au termen de 5 ani?",answer:"Nu. Regula menționată privește registrele obligatorii și documentele justificative contabile. Alte categorii, litigii sau obligații speciale pot impune păstrarea în continuare. Consultați sursa și nomenclatorul aplicabil.",request:"Evaluare arhivă contabilă",related:"logistica"},
 {slug:"avocatura",name:"Avocatură",short:"Dosare distincte. Acces justificat.",tag:"Clienți & cauze",title:"Documentele unei cauze, păstrate în context.",intro:"Organizați corespondența, înscrisurile și versiunile de lucru după client și dosar. Regimul de confidențialitate se stabilește înaintea oricărui transfer.",color:"blue",file:"Dosar cauză · AV-018",fields:[["Client","Client demonstrativ"],["Dosar intern","AV-018"],["Categorie","Înscrisuri"],["Stadiu","Arhivă de lucru"]],problem:"Un nume de fișier nu spune cine are dreptul să citească documentul.",outcome:"Evaluarea pornește de la tipurile de informații și de la persoanele autorizate. Pentru un proiect digital, furnizorii, accesul și folosirea modelelor AI trebuie agreate explicit.",steps:[["Separare client și cauză","Structurăm dosarele fără a reuni informații din mandate diferite."],["Selecția documentelor","Stabiliți ce poate fi externalizat și în ce condiții, inclusiv pentru eșantionul de evaluare."],["Predare și închidere","Agreăm inventarul, formatele de retur și modul de eliminare a copiilor la final."]],question:"Putem evalua fluxul fără dosare reale?",answer:"Da. Putem începe cu o structură de inventar și documente anonimizate sau fictive. Nu trimiteți înscrisuri confidențiale prin mesajul inițial; canalul și condițiile de prelucrare se stabilesc separat.",request:"Evaluare arhivă cabinet de avocatură",related:"notari"},
 {slug:"notari",name:"Notariat",short:"Evidență riguroasă, act cu act.",tag:"Acte & registre",title:"Un reper precis pentru fiecare act din arhivă.",intro:"Ani, registre, numere și tipuri de acte: o structură de lucru adaptată identificatorilor folosiți deja în biroul notarial.",color:"teal",file:"Fișă de inventar · N-036",fields:[["An","2024"],["Registru","Registru demonstrativ"],["Număr","036"],["Categorie","Act notarial fictiv"]],problem:"Regăsirea pornește de la registru și număr, nu de la un folder generic.",outcome:"Exemplul de inventar păstrează identificatorii actului și legătura cu unitatea arhivistică. Condițiile de păstrare și orice transfer se verifică în raport cu reglementările profesiei.",steps:[["Analiza evidenței existente","Pornim de la registrele și identificatorii utilizați în birou."],["Digitalizare controlată","Stabilim ce poate fi scanat, formatul și verificarea corespondenței cu originalul."],["Condiții profesionale","Nu presupunem că un model general de depozitare sau un termen contabil se aplică arhivei notariale."]],question:"Copia scanată înlocuiește originalul actului?",answer:"Nu prin simpla scanare. Copia digitală facilitează consultarea, iar regimul originalului rămâne cel prevăzut de lege și de normele profesiei. Orice proiect pornește de la aceste condiții.",request:"Evaluare arhivă birou notarial",related:"avocatura"}
];
export const FAQ: [string,string][] = [
 ["Cu ce putem începe?","Cu tipul documentelor, volumul aproximativ și problema pe care doriți să o rezolvați. Primul mesaj nu are nevoie de copii ale actelor. Pentru evaluare, stabilim ulterior un eșantion și condițiile de acces."],
 ["Putem păstra originalele la sediul nostru?","Da, proiectul poate fi evaluat pentru digitalizare fără depozitare externă. Locul de lucru, transportul și predarea originalelor se stabilesc în oferta pentru documentele dumneavoastră."],
 ["Documentele ajung la un model AI?","În demonstrația de pe acest site, nu: exemplele sunt fictive și rulează în browser. Într-un serviciu de căutare AI, întrebarea și fragmente din documente pot fi trimise unui model pentru a compune răspunsul. Furnizorul, locația procesării, păstrarea și eventuala utilizare pentru antrenare se clarifică înainte de a transmite documente reale."],
 ["Când primim un preț?","După evaluarea volumului, stării documentelor, indexării și serviciilor cerute. Nu există un tarif unic public și nici un termen de ofertare garantat pe site. Oferta scrisă trebuie să separe lucrările inițiale, serviciile recurente și operațiunile la cerere."]
];
