export type DemoDocument={id:string;kind:string;title:string;question:string;answer:string;source:string;page:number;pages:{heading:string;paragraphs:string[];highlight?:number}[];keywords:string[]};
export const DOCUMENTS:DemoDocument[]=[
 {id:"contract",kind:"Contract",title:"Contract de servicii · DEMO-024",question:"Care este termenul de plată?",answer:"Termenul de plată este de 30 de zile calendaristice de la primirea facturii.",source:"Art. 4.2 · Condiții de plată",page:2,keywords:["plata","plată","contract","termen"],pages:[
  {heading:"Contract de servicii",paragraphs:["Document fictiv DEMO-024 / 12 februarie 2026","Acest document este creat exclusiv pentru demonstrația 3S. Companiile și condițiile menționate sunt fictive; documentul nu produce efecte juridice.","1. Părți: Companie Exemplu A și Companie Exemplu B.","2. Obiect: pregătirea unui inventar demonstrativ de documente.","3. Durată: de la 1 martie la 31 mai 2026. Condițiile financiare sunt descrise pe pagina următoare."]},
  {heading:"Condiții de plată și predare",highlight:2,paragraphs:["Contract demonstrativ DEMO-024 / pagina 2","4.1. Factura se emite la predarea inventarului demonstrativ.","4.2. Termenul de plată este de 30 de zile calendaristice de la primirea facturii.","4.3. Primirea facturii se confirmă prin corespondența părților fictive.","5. Predarea constă în inventarul convenit pentru exemplul de lucru.","Exemplu educativ. Nu folosiți acest document ca model de contract."]}
 ]},
 {id:"factura",kind:"Factură",title:"Factură fictivă · DEMO-108",question:"Cui este adresată factura?",answer:"Factura este adresată companiei fictive Atelier Exemplu SRL.",source:"Destinatar · Pagina 1",page:1,keywords:["factura","factură","adresata","adresată","destinatar"],pages:[{heading:"Factură demonstrativă",highlight:2,paragraphs:["Exemplu DEMO-108 / 6 martie 2026","Emitent: Companie Demonstrativă. Aceste date sunt fictive.","Destinatar: Atelier Exemplu SRL.","Descriere: serviciu demonstrativ de inventariere.","Document fără valoare fiscală. Nu conține date bancare sau date ale unui client real."]}]},
 {id:"receptie",kind:"Proces-verbal",title:"Recepție lucrări · DEMO-017",question:"Ce document lipsește la recepție?",answer:"În exemplu, certificatul de conformitate al echipamentului P-04 trebuie completat la dosar.",source:"Constatări · Punctul 3",page:1,keywords:["receptie","recepție","lipseste","lipsește","document","certificat"],pages:[{heading:"Proces-verbal de recepție",highlight:3,paragraphs:["Exemplu DEMO-017 / 18 aprilie 2026","Obiectiv fictiv: Atelier Nord, corp B.","1. Au fost prezentate planurile de execuție, revizia 03.","3. Certificatul de conformitate al echipamentului P-04 trebuie completat la dosar.","4. Lista este un exemplu de conținut pentru demonstrație, nu un proces-verbal real."]}]}
];
function normalizeQuery(value:string){return value.toLocaleLowerCase("ro").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[?!.]/g,"").replace(/\s+/g," ").trim();}
export function findDocument(query:string){
 const text=normalizeQuery(query);
 const aliases:Record<string,string[]>={contract:["termen de plată","termenul de plată","contract"],factura:["destinatar factură","factură"],receptie:["document lipsă la recepție","proces-verbal"]};
 return DOCUMENTS.find(d=>[d.question,...aliases[d.id]].some(q=>normalizeQuery(q)===text));
}
