"use client";
import {useState} from "react";
import {EMAIL,emailLink} from "@/content/catalog";
import Icon from "./Icon";
export default function ContactComposer({initialSubject="Evaluare arhivă"}:{initialSubject?:string}){
 const [subject,setSubject]=useState(initialSubject);const [details,setDetails]=useState("");const [status,setStatus]=useState("");
 const body=`Bună ziua,\n\nVă contactez pentru proiectul 3S.\nSubiect: ${subject}\n\n${details.trim()||"Aș dori să discutăm despre arhivarea documentelor organizației noastre."}\n\nCu mulțumiri,\n`;
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setStatus(text===EMAIL?"Adresa a fost copiată.":"Mesajul a fost copiat. Îl puteți lipi în aplicația de e-mail.");}catch{setStatus("Copierea automată nu este disponibilă. Selectați și copiați manual adresa sau textul mesajului.");}}
 return <div className="contact-composer"><div className="composer-heading"><Icon name="mail"/><h2>Pregătiți e-mailul</h2></div><p>Completați contextul, apoi deschideți aplicația de e-mail. Dumneavoastră trimiteți mesajul.</p><div className="field"><label htmlFor="subject">Despre ce doriți să discutăm?</label><input id="subject" value={subject} onChange={e=>setSubject(e.target.value)} maxLength={120} autoComplete="off"/></div><div className="field"><label htmlFor="details">Câteva detalii despre arhivă <span>(opțional)</span></label><textarea id="details" value={details} onChange={e=>setDetails(e.target.value)} maxLength={1500} rows={5} placeholder="Tipuri de documente, volum aproximativ, localitate și ce doriți să îmbunătățiți."/><small>Nu includeți date personale din acte sau informații confidențiale.</small></div><a className="button" href={emailLink(`3S · ${subject||"Evaluare arhivă"}`,body)} onClick={()=>setStatus("Se deschide aplicația de e-mail. Mesajul nu este trimis de acest site.")}>Deschideți e-mailul <Icon/></a><button className="copy-button" onClick={()=>copy(`Către: ${EMAIL}\nSubiect: 3S · ${subject}\n\n${body}`)}><Icon name="copy" size={17}/>Copiați mesajul</button><div className="email-fallback"><span>Destinatar: <strong>{EMAIL}</strong></span><button className="icon-button" onClick={()=>copy(EMAIL)} aria-label="Copiați adresa de e-mail"><Icon name="copy" size={18}/></button></div><p className="composer-status" role="status">{status||"Textul rămâne în această pagină până când îl deschideți în aplicația de e-mail sau îl copiați."}</p></div>;
}
