import Link from "next/link";
import Image from "next/image";
import Icon from "./Icon";
import {SECTORS,FAQ} from "@/content/catalog";
export function Action({label="Să discutăm despre arhiva dumneavoastră",context="",light=false}:{label?:string;context?:string;light?:boolean}) {return <Link className={`button ${light?"button-light":""}`} href={context?`/contact?subiect=${encodeURIComponent(context)}`:"/contact"}>{label}<Icon/></Link>;}
export function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow"><span/>{children}</p>;}
export function PageIntro({eyebrow,title,intro,children}:{eyebrow:string;title:string;intro:string;children?:React.ReactNode}){return <section className="page-intro container"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1><p className="lead">{intro}</p>{children}</section>;}
export function Photo({kind="scan",className=""}:{kind?:"scan"|"archive";className?:string}){return <figure className={`photo ${className}`}><Image src={`/images/${kind}.webp`} alt={kind==="scan"?"Ilustrație fotorealistă: pregătirea documentelor la un scaner profesional":"Ilustrație fotorealistă: preluarea unei cutii dintr-un raft de arhivă"} width={1536} height={1024} sizes="(max-width: 760px) 100vw, 50vw"/><figcaption>Imagine ilustrativă generată cu AI. Nu prezintă sediul sau personalul ADRIA.</figcaption></figure>;}
export function CTA({title="Să punem arhiva în ordine.",text="Spuneți-ne ce documente aveți și unde se blochează lucrul. De aici începe o evaluare utilă.",context=""}:{title?:string;text?:string;context?:string}){return <section className="cta-band"><div className="container cta-inner"><div><Eyebrow>Următorul pas</Eyebrow><h2>{title}</h2><p>{text}</p></div><Action label="Pregătiți mesajul" context={context} light/></div></section>;}
export function SectorLinks({compact=false}:{compact?:boolean}){return <div className={`sector-grid ${compact?"compact":""}`}>{SECTORS.map((s,i)=><Link className={`sector-link ${s.color}`} href={`/solutii/${s.slug}`} key={s.slug}><span className="sector-index">0{i+1}</span><div><h3>{s.name}</h3><p>{s.short}</p></div><Icon/></Link>)}</div>;}
export function Questions({items=FAQ}:{items?:[string,string][]}){return <div className="questions">{items.map(([q,a])=><details key={q}><summary>{q}<Icon name="plus"/></summary><p>{a}</p></details>)}</div>;}
export function DocumentCard({title,fields,label="Exemplu de inventar"}:{title:string;fields:[string,string][];label?:string}){return <div className="document-card"><div className="document-bar"><Icon name="file"/><span>{label}</span><span className="small-dot"/></div><div className="document-paper"><p className="paper-kicker">3S / DOCUMENT DEMONSTRATIV</p><h2>{title}</h2><dl>{fields.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="paper-lines" aria-hidden="true"><i/><i/><i/></div><p className="paper-note">Date fictive. Structură ilustrativă.</p></div><div className="document-bottom"><Icon name="check" size={16}/>Referință comună pentru original și copie</div></div>;}
