import type {Metadata} from "next";
import Link from "next/link";
import {Action,CTA,Eyebrow,PageIntro,Questions} from "@/components/Elements";
import Icon from "@/components/Icon";
import SearchDemo from "@/components/SearchDemo";
export const metadata:Metadata={"title": "De la arhivă la documentul de care aveți nevoie", "description": "Evaluare, inventar, digitalizare și consultare. Vedeți pașii unui proiect de arhivare și încercați demonstrația cu documente fictive.", "alternates": {"canonical": "/cum-functioneaza"}};
export default function Page(){return <main>
<PageIntro eyebrow="Cum funcționează" title="O legătură clară între hârtie, inventar și informație." intro="Nu fiecare arhivă are nevoie de aceleași servicii. Stabilim mai întâi ce păstrați, ce consultați și ce doriți să găsiți mai ușor."><Action label="Descrieți-ne arhiva"/></PageIntro>
<section className="container process-timeline"><article><span>01</span><div><h2>Evaluare și scop</h2><p>Tipuri de documente, perioadă, volum și frecvența consultării. Separăm nevoile de păstrare de cele de acces digital.</p><small>Rezultat de agreat: ce intră în proiect.</small></div></article><article><span>02</span><div><h2>Inventar și preluare</h2><p>Definim identificatorii, lista dosarelor și condițiile de predare. Originalul trebuie să poată fi urmărit și după scanare.</p><small>Rezultat de agreat: inventarul și documentele de predare.</small></div></article><article id="digitalizare"><span>03</span><div><h2>Scanare și verificare</h2><p>Pregătirea hârtiei, scanarea și verificarea lizibilității sunt operațiuni distincte. OCR face textul căutabil, dar rezultatul trebuie verificat pe eșantion.</p><small>Rezultat de agreat: fișiere, câmpuri de index și criterii de acceptare.</small></div></article><article><span>04</span><div><h2>Consultare și căutare</h2><p>Stabilim cine consultă documentele și prin ce mecanism. Pentru căutare AI, precizăm furnizorii și prelucrarea datelor înainte de configurare.</p><small>Rezultat de agreat: acces, funcții și condiții de utilizare.</small></div></article><article><span>05</span><div><h2>Predare și continuitate</h2><p>Formatele de export, returul originalelor și operațiunile de închidere trebuie să fie clare de la început.</p><small>Rezultat de agreat: ce primiți și ce se întâmplă cu fiecare copie.</small></div></article></section>
<section className="demo-section" id="demonstratie"><div className="container"><div className="section-heading"><div><Eyebrow>Încercați principiul</Eyebrow><h2>Răspunsul este util.<br/>Sursa îl face verificabil.</h2></div><p>Alegeți o întrebare, deschideți documentul și verificați pasajul evidențiat. Puteți descărca exemplul integral.</p></div><SearchDemo/></div></section><section className="container section faq-section"><div><Eyebrow>Înainte de configurare</Eyebrow><h2>Detaliile se stabilesc<br/>înaintea accesului.</h2><Link className="text-link" href="/securitate">Cum abordăm securitatea<Icon/></Link></div><Questions/></section><CTA/>
</main>;}
