import type {Metadata} from "next";
import Link from "next/link";
import {CTA,Eyebrow,PageIntro,Questions} from "@/components/Elements";
import Icon from "@/components/Icon";

export const metadata:Metadata={"title": "Acces, prelucrare și securitatea documentelor", "description": "Ce trebuie stabilit pentru documente fizice, copii digitale și căutare AI: acces, furnizori, condiții de prelucrare, export și închidere.", "alternates": {"canonical": "/securitate"}};
export default function Page(){return <main>
<PageIntro eyebrow="Securitate și responsabilitate" title="Controlul documentelor începe cu reguli clare." intro="Accesul, traseul datelor și finalul contractului trebuie explicate înainte de preluare. Acestea sunt punctele pe care le stabilim pentru un proiect real."/>
<section className="container security-flow" aria-label="Traseul unui document"><div><Icon name="file" size={32}/><h2>Original</h2><p>Inventar și responsabil</p></div><Icon/><div><Icon name="scan" size={32}/><h2>Copie digitală</h2><p>Format, acces și stocare</p></div><Icon/><div><Icon name="search" size={32}/><h2>Consultare</h2><p>Sursă verificabilă</p></div></section>
<section className="container section security-controls"><article><span>01 / Documente fizice</span><h2>Cine preia și cine consultă.</h2><p>Identificăm operatorul, documentele predate și persoanele autorizate să solicite consultări. Condițiile de transport, păstrare și retur apar în contract.</p></article><article><span>02 / Copii digitale</span><h2>Unde sunt datele și cine are acces.</h2><p>Pentru implementare se precizează furnizorii, locațiile de prelucrare, drepturile de acces, copiile de siguranță și modul de raportare a incidentelor. Funcțiile disponibile se precizează în oferta și contractul proiectului.</p></article><article><span>03 / Căutare AI</span><h2>Ce ajunge la model.</h2><p>O implementare AI poate transmite întrebarea și fragmente de document către model pentru a formula un răspuns. Inferența, păstrarea datelor și antrenarea sunt operațiuni diferite; fiecare se clarifică separat.</p></article><article><span>04 / Ieșire din proiect</span><h2>Ce primiți înapoi.</h2><p>Agreăm formatele de export, metadatele, returul originalelor, tratarea copiilor de siguranță și dovada operațiunilor de închidere. Termenele și costurile se precizează în contract.</p></article></section>
<section className="soft-section"><div className="container section security-demo-note"><Icon name="shield" size={36}/><div><h2>Ce se întâmplă în demonstrația de pe site?</h2><p>Documentele sunt fictive. Întrebările sunt procesate local pentru alegerea unui exemplu predefinit. Nu puteți încărca acte și nu este contactat un model AI. Demo-ul explică principiul, fără a proba securitatea unei viitoare implementări.</p><Link className="text-link" href="/cum-functioneaza#demonstratie">Încercați demonstrația<Icon/></Link></div></div></section><section className="container section faq-section"><div><Eyebrow>Înainte de un proiect real</Eyebrow><h2>Întrebări care merită<br/>un răspuns scris.</h2></div><Questions items={[["Există o promisiune generală de găzduire în UE?","Nu pe baza acestui site. Locațiile pentru documente, copii de siguranță și procesare AI trebuie confirmate pentru implementarea aleasă, împreună cu furnizorii implicați."],["Este disponibil un jurnal complet al accesului?","Funcțiile de jurnalizare și export se verifică în soluția oferită și se precizează contractual. Demonstrația nu reprezintă o dovadă că aceste funcții sunt disponibile într-un serviciu contractat."],["Putem trimite documente reale pentru evaluare?","Numai după stabilirea unui canal și a condițiilor de prelucrare. În primul e-mail descrieți arhiva fără a atașa acte confidențiale."]]}/></section><CTA context="Clarificare acces și condiții de prelucrare"/>
</main>;}
