import type {Metadata} from "next";
import Link from "next/link";
import {CTA,Eyebrow} from "@/components/Elements";
import Icon from "@/components/Icon";

export const metadata:Metadata={"title": "Despre 3S și serviciile de arhivare prin ADRIA", "description": "3S este proiectul Scan Store Solve. Descoperiți rolul ADRIA în arhivarea fizică și digitalizare și modul în care se evaluează partea digitală.", "alternates": {"canonical": "/despre"}};
export default function Page(){return <main>
<section className="container about-hero"><div><Eyebrow>Despre 3S</Eyebrow><h1>Experiența arhivei.<br/>Perspectiva digitală.</h1><p className="lead">3S înseamnă Scan Store Solve: un proiect care aduce împreună organizarea documentelor, păstrarea lor și accesul la informație.</p></div><div className="brand-art" aria-label="3S: Scan, Store, Solve"><span>3S<span className="logo-dot"/></span><div><p>Scan.</p><p>Store.</p><p>Solve.</p></div></div></section>
<section className="container section about-roles"><article><Eyebrow>Arhivare și digitalizare</Eyebrow><h2>Activitatea ADRIA.</h2><p>ADRIA SERVICII ARHIVARE SRL este operatorul existent de arhivare din spatele acestei direcții de servicii. Datele ADRIA identifică această societate, nu o societate nouă cu numele 3S.</p><dl className="identity-list"><div><dt>Denumire</dt><dd>ADRIA SERVICII ARHIVARE SRL</dd></div><div><dt>Cod fiscal</dt><dd>30901492</dd></div><div><dt>Registrul comerțului</dt><dd>J03/1580/2012</dd></div><div><dt>Punct de lucru publicat</dt><dd>Str. Gării nr. 29 bis, Hala C1, Golești, Argeș</dd></div></dl><a className="text-link" href="https://adriaarhivare.ro/contact.html" target="_blank" rel="noreferrer">Contactul public ADRIA (filă nouă)<Icon/></a></article><article><Eyebrow>Direcția digitală</Eyebrow><h2>Proiectul 3S.</h2><p>3S este prezentat aici ca proiect și marcă de lucru. Acest site nu vinde abonamente și nu oferă autentificare într-o platformă de documente.</p><p>Căutarea cu sursă este explicată printr-o demonstrație predefinită. Pentru o implementare reală, funcțiile, furnizorii și condițiile de prelucrare se stabilesc în evaluare și în documentele contractuale.</p><Link className="text-link" href="/cum-functioneaza#demonstratie">Deschideți demonstrația<Icon/></Link><div className="about-note"><Icon name="shield"/><p>Entitatea contractantă și serviciile incluse sunt precizate în ofertă, înainte de orice predare de documente.</p></div></article></section>
<section className="soft-section"><div className="container section"><div className="section-heading"><div><Eyebrow>Felul în care lucrăm</Eyebrow><h2>Responsabilități clare.<br/>De la început.</h2></div><p>Un proiect bun are atât un responsabil pentru documente, cât și unul pentru prelucrarea digitală.</p></div><div className="three-columns"><article><span className="step-index">01</span><h3>Organizația dumneavoastră</h3><p>Stabilește documentele, obligațiile, utilizatorii și ce înseamnă un rezultat util.</p></article><article><span className="step-index">02</span><h3>Operatorul de arhivare</h3><p>Definește preluarea, inventarierea, păstrarea și consultarea în limitele serviciilor contractate.</p></article><article><span className="step-index">03</span><h3>Implementarea digitală</h3><p>Definește formatele, indexarea, accesul și furnizorii implicați în proiectul digital.</p></article></div></div></section><CTA/>
</main>;}
